---
title: "p8105_hw5_jl5934"
author: "Jesus Luevano"
date: "2023-11-03"
output: html_document
---

```{r}
library(tidyverse)
```

# Problem 1 - WaPo

```{r WaPo dataset read}
WaPo.df <- read_csv("data/homicide-data.csv") %>%
  janitor::clean_names()
```

The data includes `r print(colnames(WaPo.df))`, with a total of `r nrow(WaPo.df)` observations. 

```{r WaPo tidy}
WaPo.df %>%
  mutate(city_state = 
           paste0(city,", ",state)) %>%
  filter(disposition %in% c("Closed without arrest", "Open/No arrest")) %>%
  group_by(city_state, disposition) %>%
  summarize(n_obs = n()) %>%
  pivot_wider(names_from = disposition,
              values_from = n_obs
  )
  
```

```{r WaPO filter,eval=FALSE }
WaPo.df %>%
  mutate(city_state = 
           paste0(city,", ",state)) %>%
  filter(city_state == "Baltimore, MD") %>%
  count(filter(city_state == "Baltimore, MD", disposition %in% c("Closed without arrest", "Open/No arrest")))
  
  #prop.test(x = count())
```


# Problem 2

```{r prep trial data}
file_list <- list.files("data/data/")

file_reader = function(x) {
  
  data_x = read_csv(paste0("data/data/", x))
  name_x = gsub(".csv","",x)
  
  tibble(
    name = name_x,
    data = as.data.frame(data_x)
  ) %>% 
  unnest(cols = data)
    
}

output = map(file_list, file_reader) %>%
  bind_rows() %>%
  pivot_longer(
    cols = week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "value"
  ) %>%
  rename("subject" = "name") %>%
  mutate(group = 
           ifelse(subject %in% c("con_01","con_02","con_03","con_04","con_05","con_06","con_07","con_08","con_09","con_10"), "control", "experimental"))

```

```{r plot trial data}
ggplot(data = output, aes(x = week, y = value, group = subject)) +
geom_line(aes(color = group))
```


# Problem 3

sim_data = tibble(
    x = rnorm(n = 30, mean = 0, sd = 5),
    mu = 0
  )
t_test = broom::tidy(t.test(sim_data, mu = 0))
sim_data |> 
    mutate(
      estimate = summarize(t_test[["estimate"]]),
      p_value = summarize(t_test[["p.value"]])
    )


sim_data <- sim_data |> 
    summarize(
      mu_hat = t_test[["estimate"]],
      p_value = t_test[["p.value"]]
    ) 

```{r create sim_0}
#mu_list = 0:6
output_sim = vector("list", 5000)
file_list = 1:5000

sim_mean_test = function(n = 30, mu = 0, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma), 
    mu = mu
  )
  
  t_test = broom::tidy(t.test(sim_data, mu = mu))
  
  power_data = tibble(
    estimate = t_test[["estimate"]],
    p_value = t_test[["p.value"]],
    mean = mu
    )
}

output_sim_0 = map(file_list, sim_mean_test) %>%
  bind_rows() #%>%   mutate(mu = mu_list)

```


```{r create sim1:6}
output_sim = vector("list", 5000)
file_list = 1:5000

sim_mean_test = function(n = 30, mu = 1, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma), 
    mu = mu
  )
  
  t_test = broom::tidy(t.test(sim_data, mu = mu))
  
  power_data = tibble(
    estimate = t_test[["estimate"]],
    p_value = t_test[["p.value"]],
    mean = mu
    )
}

output_sim_1 = map(file_list, sim_mean_test) %>%
  bind_rows() #%>%   mutate(mu = mu_list)

output_sim = vector("list", 5000)
file_list = 1:5000

sim_mean_test = function(n = 30, mu = 2, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma), 
    mu = mu
  )
  
  t_test = broom::tidy(t.test(sim_data, mu = mu))
  
  power_data = tibble(
    estimate = t_test[["estimate"]],
    p_value = t_test[["p.value"]],
    mean = mu
    )
}

output_sim_2 = map(file_list, sim_mean_test) %>%
  bind_rows() #%>%   mutate(mu = mu_list)

output_sim = vector("list", 5000)
file_list = 1:5000

sim_mean_test = function(n = 30, mu = 3, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma), 
    mu = mu
  )
  
  t_test = broom::tidy(t.test(sim_data, mu = mu))
  
  power_data = tibble(
    estimate = t_test[["estimate"]],
    p_value = t_test[["p.value"]],
    mean = mu
    )
}

output_sim_3 = map(file_list, sim_mean_test) %>%
  bind_rows() #%>%   mutate(mu = mu_list)

output_sim = vector("list", 5000)
file_list = 1:5000

sim_mean_test = function(n = 30, mu = 4, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma), 
    mu = mu
  )
  
  t_test = broom::tidy(t.test(sim_data, mu = mu))
  
  power_data = tibble(
    estimate = t_test[["estimate"]],
    p_value = t_test[["p.value"]],
    mean = mu
    )
}

output_sim_4 = map(file_list, sim_mean_test) %>%
  bind_rows() #%>%   mutate(mu = mu_list)

output_sim = vector("list", 5000)
file_list = 1:5000

sim_mean_test = function(n = 30, mu = 5, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma), 
    mu = mu
  )
  
  t_test = broom::tidy(t.test(sim_data, mu = mu))
  
  power_data = tibble(
    estimate = t_test[["estimate"]],
    p_value = t_test[["p.value"]],
    mean = mu
    )
}

output_sim_5 = map(file_list, sim_mean_test) %>%
  bind_rows() #%>%   mutate(mu = mu_list)

output_sim = vector("list", 5000)
file_list = 1:5000

sim_mean_test = function(n = 30, mu = 6, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma), 
    mu = mu
  )
  
  t_test = broom::tidy(t.test(sim_data, mu = mu))
  
  power_data = tibble(
    estimate = t_test[["estimate"]],
    p_value = t_test[["p.value"]],
    mean = mu
    )
}

output_sim_6 = map(file_list, sim_mean_test) %>%
  bind_rows() #%>%   mutate(mu = mu_list)
```

```{r merge all}
output_sum_all <- bind_rows(output_sim_0, output_sim_1, output_sim_2, output_sim_3, output_sim_4, output_sim_5, output_sim_6) %>%
  mutate(significant = ifelse(p_value < 0.05, "reject_null", "not_reject_null"))
```

```{r plot power}
ggplot(output_sum_all, aes(x = mean, fill = factor(significant))) +
  geom_bar(position = "fill")
```

```{r plot mean sample vs population}
ggplot(output_sum_all, aes(x = mean, y = estimate)) + 
  geom_point()

output_sum_all %>%
  filter(significant == "reject_null") %>%
  ggplot(aes(x = mean, y = estimate)) +
  geom_point()
```

